// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/dnsLookup': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dnsLookup').default>>>>
    }
    '/api/macLookup': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/macLookup').default>>>> | Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/macLookup').default>>>> | Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/macLookup').default>>>>
    }
    '/api/ping': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ping').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.4_ioredis@5.4.1_magicast@0.3.5_rollup@4.24_2k7m6tt7b46bgsxaiirz4m7r34/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}