// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/10/2024, 1:03:51 PM
const configMerger = require("/Users/jessejesse/Desktop/untitled folder 14/NetWise/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.5_rollup@4.24.0/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/jessejesse/Desktop/untitled folder 14/NetWise/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/plugins/**/*.{js,ts,mjs}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/composables/**/*.{js,ts,mjs}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/utils/**/*.{js,ts,mjs}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jessejesse/Desktop/untitled folder 14/NetWise/app.config.{js,ts,mjs}"] }));

module.exports = config
